### ISSUE TITLE
Thanks,love to see cloze support!💕

### ISSUE THREAD

**Issue by glitchlover** [kangruixiang/Ankify#12]
I cannot believe how easy it is to add anki cards thanks!
Any plan for cloze?

**Comment by kangruixiang** [comment]
Yes it's doable. The biggest problem would be updating the note. Any changes to the note would mean anki imports it as a different card. The way around it would be either to have an unique ID for each card or to parse the ID from anki itself. So that would be the biggest obstacle I think.

**Comment by kangruixiang** [comment]
Hi there, I've added support for cloze now.
