### ISSUE TITLE
Failed to Run Script Ankify?

### ISSUE THREAD

**Issue by abhiraj-saxena** [kangruixiang/Ankify#2]
Hey,
I followed your tutorial and made my Typora notes like how you suggested. However, when I click the folder that has both the .md file and the folder with all the jpeg files, Ankify tells me that it failed to run the script. I do see a .html folder but it is empty. Any thoughts?

I'm on windows by the way!

**Comment by kangruixiang** [comment]
Issue solved over on reddit
