### ISSUE TITLE
Brilliant

### ISSUE THREAD

**Issue by DutchPete** [kangruixiang/Ankify#5]
This exactly what I need to turn some of my zettelkasten notes into Anki cards.
I am on macOS, so cannot use this 😞

**Comment by kangruixiang** [comment]
Hi, thanks for commenting. I'll plan for Mac support within the next week or so.

**Comment by DutchPete** [comment]
> Hi, thanks for commenting. I'll plan for Mac support within the next week or so.

As you stated on the Obsidian forum. I am looking forward to it.

**Comment by kangruixiang** [comment]
I added MAC support. It worked on my macbook. See if you get any errors. I would try on a backup folder first.
